condense_wildcard_suffixes  = true
format_code_in_doc_comments = true
format_strings              = true
group_imports               = "StdExternalCrate"
imports_granularity         = "Module"
license_template_path       = ".build/license-header.txt"
normalize_comments          = true
normalize_doc_attributes    = true
reorder_impl_items          = true
use_field_init_shorthand    = true
version                     = "Two"
wrap_comments               = true
