on:
  pull_request: # Required to only listen to pull request events, else it will always fail
    types: [opened, reopened, ready_for_review] # Recommended

jobs:
  cpr:
    runs-on: ubuntu-latest
    steps:
      - name: Validates the pull request
        uses: Namchee/conventional-pr@v0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          close: false
          commit_pattern: "([\\w\\-]+)(\\([\\w\\-]+\\))?!?: [\\w\\s:\\-]+"
