on:
  pull_request:

jobs:
  cpr:
    runs-on: ubuntu-latest
    steps:
      - name: Validates the pull request
        uses: Namchee/conventional-pr@v0.6.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          close: false
          commit_pattern: "([\\w\\-]+)(\\([\\w\\-]+\\))?!?: [\\w\\s:\\-]+"
